services:
  # Backend API Service - FREE TIER
  - type: web
    name: nexusapp-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: # You'll add MongoDB Atlas free connection string here
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://nexusapp-frontend.onrender.com

  # Frontend Next.js Service - FREE TIER
  - type: web
    name: nexusapp-frontend
    runtime: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://nexusapp-backend.onrender.com

# Using external MongoDB Atlas (free) instead of paid Render database